# Learn more about configuring your app at https://shopify.dev/docs/apps/tools/cli/configuration

name = "qr-code-app"
client_id = "c280478c42622791656ef2cb030362c6"
application_url = "https://hammer-declaration-analyze-township.trycloudflare.com"
embedded = true

[access_scopes]
# Learn more at https://shopify.dev/docs/apps/tools/cli/configuration#access_scopes
scopes = "write_products"

[auth]
redirect_urls = [
  "https://hammer-declaration-analyze-township.trycloudflare.com/auth/callback",
  "https://hammer-declaration-analyze-township.trycloudflare.com/auth/shopify/callback",
  "https://hammer-declaration-analyze-township.trycloudflare.com/api/auth/callback"
]

[webhooks]
api_version = "2024-01"

[pos]
embedded = false

[build]
automatically_update_urls_on_dev = true
dev_store_url = "dulalstore.myshopify.com"
